language: ruby
rvm:
  - 2.5.0
branches:
  only:
  - master
script:
  - bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  local_dir: _site
  target_branch: production
  on:
    branch: master
