title: Binary.com Affiliates
email: affiliates@binary.com
description: > # this means to ignore newlines until "baseurl:"
  Binary.com Affiliate Program
baseurl: "" 
url: "https://affiliates.binary.com" 
twitter_username: 
github_username: 
future: true

livereload: true

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-livereload
  
exclude:
  - Gemfile
  - Gemfile.lock