# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Binary.com - Binary Options Trading Affiliate Program
email: marketing@binary.com
description: > # this means to ignore newlines until "baseurl:"
  Join Binary.com's affiliate program now. Start earning commission through the premier platform for binary options trading since 1999.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://affiliates.binary.pw" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
